### ISSUE TITLE
Client-side Weapons

### ISSUE THREAD

**Issue by respectZ** [euphori/Dummy-Project-RGL#2]
- [x] Add `blend_transition` and `blend_via_shortest_path` in the default states.
https://github.com/euphori/Dummy-Project-RGL/blob/b988099924f90098b641693940dc08b62f17d85b/packs/RP/animation_controllers/weapon/golden_kings_excalibur.ac.json#L14-L16
https://github.com/euphori/Dummy-Project-RGL/blob/b988099924f90098b641693940dc08b62f17d85b/packs/RP/animation_controllers/weapon/nether_sickle.ac.json#L24-L26
- [x] Transitions
All transitions seem like not handled properly.
- Remove unnecessary conditions
- Simplify the conditions
- Consider every next possible action
eg:
https://github.com/euphori/Dummy-Project-RGL/blob/b988099924f90098b641693940dc08b62f17d85b/packs/RP/animation_controllers/weapon/golden_kings_excalibur.ac.json#L115-L138
https://github.com/euphori/Dummy-Project-RGL/blob/b988099924f90098b641693940dc08b62f17d85b/packs/RP/animation_controllers/weapon/nether_sickle.ac.json#L121-L144
```json
{
  "attack_basic1": {
    "blend_transition": 0.3,
    "blend_via_shortest_path": true,
    "animations": ["golden_kings_excalibur.tpp.attack_basic1"],
    "transitions": [
      {
        "attack_basic2": "q.property('dummy:atk_state') == 2"
      },
      {
        "initial": "!q.is_item_name_any('slot.weapon.mainhand','dummy:golden_kings_excalibur')"
      },
      {
        "check": "q.is_emoting"
      },
      {
        "knight_awakened": "q.property('dummy:atk_state') == -1"
      },
      {
        "run": "q.property('dummy:atk_state') == 0 && q.modified_move_speed>0.14 && !q.is_sneaking"
      },
      {
        "sneak": "q.property('dummy:atk_state') == 0 && q.is_sneaking"
      },
      {
        "default": "q.property('dummy:atk_state') == 0"
      }
    ]
  }
}
```
- [x] Split body and leg animation controller
Player can move and attack at the same time, so it's necessary to have both of them as a separate controller.

- [ ] Implement fpp animations
- [x] Convert animation `catmullrom` / smooth keyframes into linear.
![image](https://github.com/euphori/Dummy-Project-RGL/assets/12747304/30a9ea93-4015-464c-889d-1e9918244985)
![image](https://github.com/euphori/Dummy-Project-RGL/assets/12747304/b022db32-14fb-48c0-938d-ec94d2ce44a8)

**Comment by euphori** [comment]
there isnt any fpp animations available

**Comment by respectZ** [comment]
My bad, just ignore it then for now. I'll add the in-depth details later.
